POST {{host}}/backoffice/api/postStaff.php
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="staff-username"

robink
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="staff-firstname"

Robin
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="staff-lastname"

Keppens
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="staff-nickname-1"


--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="staff-nickname-2"

Mang
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="staff-email"

robinkep@gmail.com
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="staff-mobile"

0488810092
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="staff-totem"

Wilskrachtig stekelvarken
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="staff-function"

Giverleiding
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="branch-head"


--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="staff-head"


--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="uniform-master"


--WebAppBoundary--

###
GET {{host}}/backoffice/api/getStaff.php?q=true
Accept: application/json

###
GET {{host}}/backoffice/api/getStaffDetail.php?q=robink
Accept: application/json

###

POST {{host}}/backoffice/api/getData.php
Content-Type: application/json

{
  "table": "60_year_contact",
  "fields": ["email", "firstname", "lastname"]
}

###

POST {{host}}/backoffice/api/postPassword.php
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="oldpass"

e1aaaaaaZ
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="newpass1"

azerA123
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="newpass2"

azerA123
--WebAppBoundary--

###