GET {{host}}/api/getNavigation.php
Accept: application/json

###
POST {{host}}/api/postSixtyYear.php
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="firstname"

test
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="lastname"

test
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="email"

test@test.be
--WebAppBoundary--

###

